In [303]:
import pandas as pd
from pathlib import Path

data_path = Path("data")
data_path.mkdir(exist_ok=True)

df = pd.read_csv(data_path / "data_combined.csv")
df.head()

         date  temp_min  temp_max  temp_mean   city
0  1996-05-18       6.6       8.5   7.700000  Malmö
1  1996-05-19       8.5       8.9   8.700000  Malmö
2  1996-05-20       7.4       8.4   7.800000  Malmö
3  1996-05-21       6.5       7.7   7.166667  Malmö
4  1996-05-22       6.5      11.4   9.700000  Malmö

In [304]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['city'] = le.fit_transform(df['city'])
df["date"] = pd.to_datetime(df["date"])
df['day_of_year'] = pd.to_datetime(df['date']).dt.day_of_year
df['month']       = pd.to_datetime(df['date']).dt.month
df['year']        = pd.to_datetime(df['date']).dt.year

df = df.sort_values('date').reset_index(drop=True)

In [305]:
print(df["date"].dtype)

datetime64[us]

In [306]:
df.columns

Index(['date', 'temp_min', 'temp_max', 'temp_mean', 'city', 'day_of_year',
       'month', 'year'],
      dtype='str')

In [307]:
df["city"].unique()

array([2, 0, 1])

In [308]:
le.classes_

array(['Malmö', 'Stockholm', 'Vinga A'], dtype=object)

In [309]:
from sklearn.ensemble import GradientBoostingRegressor

X = df[['city', 'day_of_year', 'month', 'year']]
y = df['temp_mean']

split = int(len(df) * 0.8)

X_train = X.iloc[:split]   # older 80% of data
X_test  = X.iloc[split:]   # newer 20% of data

y_train = y.iloc[:split]
y_test  = y.iloc[split:]

model = GradientBoostingRegressor()
model.fit(X_train, y_train)

GradientBoostingRegressor()

In [310]:
len(X_train), len(X_test), len(y_train), len(y_test)

(22768, 5692, 22768, 5692)

In [311]:
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)

mse

11.13522708811748

In [312]:
def make_input_data(date: str):
    user_date = pd.to_datetime(date)

    user_input = pd.DataFrame({
        'city': [3],
        'day_of_year': [user_date.day_of_year],
        'month':       [user_date.month],
        'year':        [user_date.year]
    })
    return user_input

In [313]:
import pandas as pd

user_input = make_input_data("2022-01-16")

predicted_temp = model.predict(user_input)
print(f"Predicted temp_mean: {predicted_temp[0]:.1f} °C")

Predicted temp_mean: 4.4 °C

In [314]:
model_low  = GradientBoostingRegressor(loss='quantile', alpha=0.1)  # 10th percentile
model_mid  = GradientBoostingRegressor(loss='quantile', alpha=0.5)  # median
model_high = GradientBoostingRegressor(loss='quantile', alpha=0.9)  # 90th percentile

model_low.fit(X_train, y_train)
model_mid.fit(X_train, y_train)
model_high.fit(X_train, y_train)

# Predict
low  = model_low.predict(user_input)[0]
mid  = model_mid.predict(user_input)[0]
high = model_high.predict(user_input)[0]

print(f"Predicted: {mid:.1f} °C  (range: {low:.1f} – {high:.1f} °C)")
print(f"+- {round((high - low) / 2)}")

Predicted: 5.3 °C  (range: 4.2 – 6.3 °C)
+- 1

In [315]:
import joblib

models_path = Path("models")
models_path.mkdir(exist_ok=True)

# Save
models = {
    'low':  model_low,
    'mid':  model_mid,
    'high': model_high
}
joblib.dump(models, models_path / 'temperature_models.pkl')

['models/temperature_models.pkl']

In [316]:
models = joblib.load(models_path / 'temperature_models.pkl')
predicted = models['mid'].predict(user_input)
predicted[0]

np.float64(5.259989336414284)

In [317]:
from xgboost import XGBRegressor

xgboost = XGBRegressor(
    n_estimators=500, 
    learning_rate=0.05,   
    max_depth=6,           
    subsample=0.8,         
    colsample_bytree=0.8,  
    random_state=42
)

xgboost

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [318]:
xgboost.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [319]:
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
import numpy as np

y_pred = xgboost.predict(X_test)

mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

mse, rmse, r2

(11.13522708811748, np.float64(3.6333450436031285), 0.7400776081974858)

In [320]:
predicted_temp = xgboost.predict(user_input)[0]
print(f"Predicted temp_mean: {predicted_temp:.1f} °C")

Predicted temp_mean: 6.0 °C

In [321]:
model_low  = XGBRegressor(objective='reg:quantileerror', quantile_alpha=0.1)
model_mid  = XGBRegressor(objective='reg:quantileerror', quantile_alpha=0.5)
model_high = XGBRegressor(objective='reg:quantileerror', quantile_alpha=0.9)

model_low.fit(X_train, y_train)
model_mid.fit(X_train, y_train)
model_high.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [322]:
X_test

       city  day_of_year  month  year
22768     0          103      4  2020
22769     1          103      4  2020
22770     0          104      4  2020
22771     1          104      4  2020
22772     2          104      4  2020
...     ...          ...    ...   ...
28455     0           30      1  2026
28456     2           30      1  2026
28457     2           31      1  2026
28458     0           31      1  2026
28459     0           32      2  2026

[5692 rows x 4 columns]

In [323]:
y_test

22768    11.25
22769     7.85
22770     5.30
22771     3.65
22772     5.85
         ...
28455    -1.30
28456    -2.20
28457    -1.45
28458    -2.80
28459    -5.00
Name: temp_mean, Length: 5692, dtype: float64

In [324]:
user_input = make_input_data("2022-01-15")

low = model_low.predict(user_input)[0]
mid = model_mid.predict(user_input)[0]
high = model_high.predict(user_input)[0]

print(f"Predicted: {mid:.1f} °C  (range: {low:.1f} – {high:.1f} °C)")
margin = round((high - low) / 2, 1)
print(f"±{margin:.1f}°C")

Predicted: 6.1 °C  (range: 5.8 – 8.1 °C)
±1.1°C

In [325]:
low_y_pred = model_low.predict(X_test)
mid_y_pred = model_mid.predict(X_test)
high_y_pred = model_high.predict(X_test)

low_mse = mean_squared_error(y_test, low_y_pred)
low_mae  = mean_absolute_error(y_test, low_y_pred)
low_rmse = np.sqrt(mean_squared_error(y_test, low_y_pred))
low_r2   = r2_score(y_test, low_y_pred)

mid_mse = mean_squared_error(y_test, mid_y_pred)
mid_mae  = mean_absolute_error(y_test, mid_y_pred)
mid_rmse = np.sqrt(mean_squared_error(y_test, mid_y_pred))
mid_r2   = r2_score(y_test, mid_y_pred)

high_mse = mean_squared_error(y_test, high_y_pred)
high_mae  = mean_absolute_error(y_test, high_y_pred)
high_rmse = np.sqrt(mean_squared_error(y_test, high_y_pred))
high_r2   = r2_score(y_test, high_y_pred)

low_mse, low_mae, low_rmse, low_r2

(12.29177508774409,
 2.672256756777,
 np.float64(3.5059627904106585),
 0.7579834788848109)

In [326]:
mid_mse, mid_mae, mid_rmse, mid_r2

(14.630773259728338,
 2.9435158729678883,
 np.float64(3.825019380307548),
 0.7119302281185453)

In [327]:
high_mse, high_mae, high_rmse, high_r2

(20.543689880196286,
 3.525371565185461,
 np.float64(4.532514741310423),
 0.5955090033634095)

In [328]:
models = {
    'low':  model_low,
    'mid':  model_mid,
    'high': model_high
}
joblib.dump(models, models_path / 'temperature_models.pkl')

['models/temperature_models.pkl']